# Generated by Django 3.2.6 on 2021-08-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
    ]
